# PostgreSQL
#   gem install pg
#
#   Ensure the pg gem is defined in your Gemfile
#   gem 'pg'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: help_find                     #insert the name of your app instead of "sample"

test:
  <<: *default
  database: help_find_test                #insert the name of your app instead of "sample"

production:
  <<: *default
  database: help_find_production          #insert the name of your app instead of "sample"
  username: help_find                     #insert the name of your app instead of "sample"
  password: <%= ENV['HELP_FIND_DATABASE_PASSWORD'] %> #insert the name of your app instead of "sample"
